# Generated by Django 3.0.4 on 2020-04-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20200429_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=120, unique=True),
        ),
    ]
