# Generated by Django 3.0.4 on 2020-04-29 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20200429_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='rest.Roles'),
        ),
    ]
