# Generated by Django 3.0.4 on 2020-05-08 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_auto_20200508_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='users',
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='rest.Roles'),
        ),
    ]
